toolshare/toolshare/Sharing/urls.py
from django.conf.urls import patterns, include, url
from Sharing import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    #+++++++++++++++ URLS related to the SHED over here+++++++++++++++++++ #
    url(r'^sheds/$', views.sheds, name='sheds'),
    url(r'^sheds/create/$', views.shedcreate, name='shedcreate'),
    url(r'^sheds/(?P<shed_id>\d+)/$',views.sheddetail, name='sheddetail'),
    url(r'^sheds/(?P<shed_id>\d+)/edit/$', views.shededit, name='shededit'),
    url(r'sheds/(?P<shed_id>\d+)/coords/$', views.shedcoords, name='shedcoords'),
    url(r'sheds/(?P<shed_id>\d+)/coords/add/$',views.shedaddcoords,name='shedaddcoords'),
    url(r'sheds/tooltransfer/(?P<tool_id>\d+)/$',views.tooltransfer,name = 'tooltransfer'),
    url(r'sheds/returntool/(?P<tool_id>\d+)/$',views.returntool,name = 'returntool'),
    #+++++++++++++++++SHED url ends here ++++++++++++++++++++++++++++++++++#
    url(r'^$', RedirectView.as_view(url='received-requests/', permanent=False), name='received-requests'),
    url(r'^create-request/(?P<tool_id>\d+)/$', views.create_request, name='create-request'),
    url(r'^create-sharing/(?P<tool_request_id>\d+)/$', views.create_sharing, name='create-sharing'),
    url(r'^received-requests/$', views.received_requests_index, name='received-requests'),
    url(r'^received-requests-coordinator/$', views.received_requests_coordinator_index, name='received-requests-coordinator'),
    url(r'^asked-requests/$', views.asked_requests_index, name='asked-requests'),
    url(r'^received-requests/(?P<tool_request_id>\d+)/$', views.received_request_detail, name='received-request-detail'),
    url(r'^asked-requests/(?P<tool_request_id>\d+)/$', views.asked_request_detail, name='asked-request-detail'),
    url(r'^asked-requests/(?P<tool_request_id>\d+)/edit$', views.asked_request_edit, name='asked-request-edit'),
    url(r'^given-tools/$', views.given_tools_index, name='given-tools'),
    url(r'^given-tools-coordinator/$', views.given_tools_coordinator_index, name='given-tools-coordinator'),
    url(r'^given-tools/(?P<tool_sharing_id>\d+)/$', views.given_tool_edit, name='given-tool-edit'),
    url(r'^borrowed-tools/$', views.borrowed_tools_index, name='borrowed-tools'),
    #++++++++++++++++++++Statistics ++++++++++++++++++++++++++++++++++++++++++++++++++++++#
    url(r'^statistics/$',views.statistics,name = "statistics"),
    #+++++++++++++++++++Search Tool Functionality ++++++++++++++++++++++++++#
    url(r'^searchtools/$', views.searchtools , name = 'searchtools'),
)

toolshare/toolshare/ToolMgmt/urls.py
from django.conf.urls import patterns, include, url
from ToolMgmt import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='tools/', permanent=False), name='tools'),
    url(r'^tools/$', views.index, name='tools'),
    url(r'^tools/mytools/', views.mytools, name='mytools'),
    url(r'^tools/register/$', views.register, name="register"),
    url(r'^tools/(?P<tool_id>\d+)/$', views.detail, name='detail'),
    url(r'^tools/(?P<tool_id>\d+)/edit/$', views.tool_edit, name='tool_editition'),
)

toolshare/toolshare/toolshare/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='home/'), name='home'),
    url(r'^home/', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('UserAuth.urls',namespace="users")),
    url(r'^toolmgmt/', include('ToolMgmt.urls', namespace="toolmgmt")),
    url(r'^sharing/', include('Sharing.urls', namespace="sharing")),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
)

toolshare/toolshare/ToolMgmt/models.py
from django.db import models
from UserAuth.models import UserProfile
from Sharing.models import ShareZone, Shed, Sharing, Request
from django.db.models import Q
from datetime import date, timedelta, datetime
from django.utils.timezone import utc
from Sharing.models import ShareZone, Shed

class ToolCategory(models.Model):
    name = models.CharField(verbose_name="Name", max_length=100)
    description = models.CharField(verbose_name="Description", max_length=200)

    def __str__(self):
        return self.name

class ToolStatus(models.Model):
    name = models.CharField(verbose_name="Name", max_length=50)
    description = models.CharField(verbose_name="Description", max_length=200)

    def __str__(self):
        return self.name

class Tool(models.Model):
    name = models.CharField(verbose_name="Name", max_length=100)
    description = models.CharField(verbose_name="Description", max_length=200)
    active = models.BooleanField(default=True)
    category = models.ForeignKey(ToolCategory, related_name='category')
    status = models.ForeignKey(ToolStatus, related_name='status')
    owner = models.ForeignKey(UserProfile, related_name='owner', null=True)
    image = models.ImageField(upload_to="images/tools/", blank=True, null=True)
    identifier = models.CharField(verbose_name="Identifier", blank=True, null=True, max_length=200)
    shed = models.ForeignKey(Shed, related_name='tools', null = True, blank = True)
    in_shed = models.BooleanField(default = False)
    blackout_start_date = models.DateTimeField(null = True, blank = True)
    blackout_end_date = models.DateTimeField(null = True, blank = True)

    def __str__(self):
        return self.name

    def is_in_shed(self):
        return self.shed!=None

    def is_available(self, from_date, to_date):
        result = False
        now = datetime.datetime.utcnow().replace(tzinfo=utc)
        tools = Request.objects.filter(Q(tool=self) & Q(approved=True) & Q(start_date__gte=now) &
                                      ((Q(start_date__lte=from_date)&Q(end_date__gte=from_date)) |
                                      (Q(start_date__lte=to_date)&Q(end_date__gte=to_date))))
        return (tools.count() == 0)

    def date_range(self, start, end):
        l = []
        for i in range((end-start).days + 1):
            l.append( str( (start+ timedelta(days=i)).date().strftime('%Y/%m/%d') ))
        return l

    def blackout_dates(self):
        return self.date_range(self.blackout_start_date, self.blackout_end_date)

toolshare/toolshare/ToolMgmt/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from ToolMgmt.models import Tool, ToolCategory, ToolStatus
from ToolMgmt.utils import Is_Owner
from UserAuth.models import UserProfile
from django.contrib import messages
from django import forms
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from itertools import chain
import pdb

@login_required(login_url='users:login')
def index(request):
    all_tools = Tool.objects.filter(owner__sharezone = request.user.profile.sharezone).filter(active=True).exclude(status_id=4)
    paginator = Paginator(all_tools, 6)
    page = request.GET.get('page')
    #

    try:
        paged_tools = paginator.page(page)
    except PageNotAnInteger:
        paged_tools = paginator.page(1)
    except EmptyPage:
        paged_tools = paginator.page(paginator.num_pages)

    return render(request, 'ToolMgmt/index.html', {'all_tools': paged_tools})

@login_required(login_url='users:login')
def mytools(request):
    my_tools = Tool.objects.filter( owner = request.user.profile)
    return render(request, 'ToolMgmt/mytools.html', {'my_tools': my_tools})

@login_required(login_url='users:login')
def register(request):
    context = RequestContext(request)
    if request.POST:
        form = ToolModelForm(request.POST, request.FILES)
        form.fields['blackout_start_date'].widget.attrs['id'] = 'datetimepicker'
        form.fields['blackout_end_date'].widget.attrs['id'] = 'datetimepicker2'
        if form.is_valid():
            new_tool = form.save()
            new_tool.owner = UserProfile.objects.get( user = request.user)
            new_tool.save()
            messages.add_message(request, messages.SUCCESS, 'Tool %s was successfully created' % new_tool)
            return HttpResponseRedirect(reverse('toolmgmt:detail', kwargs={'tool_id': new_tool.id}))
        else:
            return render_to_response('ToolMgmt/register.html', {'form': form}, context)
    else:
        form = ToolModelForm()
        form.fields['blackout_start_date'].widget.attrs['id'] = 'datetimepicker'
        form.fields['blackout_end_date'].widget.attrs['id'] = 'datetimepicker2'
        return render_to_response('ToolMgmt/register.html', {'form': form}, context)

@login_required(login_url='users:login')
def tool_edit(request, tool_id):
    context = RequestContext(request)
    tool = Tool.objects.get(id=tool_id)
    is_owner = Is_Owner(request.user.profile,tool)
    if not tool.is_in_shed():
        if is_owner:
            if request.POST:
                form = ToolModelForm(request.POST, request.FILES, instance=tool)
                form.fields['blackout_start_date'].widget.attrs['id'] = 'datetimepicker'
                form.fields['blackout_end_date'].widget.attrs['id'] = 'datetimepicker2'
                if form.is_valid():
                    new_tool = form.save()
                    new_tool.owner = UserProfile.objects.get( user = request.user)
                    new_tool.save()
                    messages.add_message(request, messages.SUCCESS, 'Tool %s was successfully edited' % new_tool)
                    return HttpResponseRedirect(reverse('toolmgmt:detail', kwargs={'tool_id': new_tool.id}))
                else:
                    return render_to_response('ToolMgmt/edit.html', {'form': form, 'tool' : tool}, context)
            else:
                form = ToolModelForm(instance=tool)
                form.fields['blackout_start_date'].widget.attrs['id'] = 'datetimepicker'
                form.fields['blackout_end_date'].widget.attrs['id'] = 'datetimepicker2'
                return render_to_response('ToolMgmt/edit.html', {'form': form, 'tool' : tool}, context)
        else:
            messages.add_message(request,messages.ERROR, 'You are not authorised to edit this tool')
            return HttpResponseRedirect(reverse('toolmgmt:detail',kwargs = {'tool_id':tool_id}))
    else:
        messages.add_message(request, messages.ERROR, 'You are not allowed to edit tool when tool is in shed')
        return HttpResponseRedirect(reverse('toolmgmt:detail',kwargs = {'tool_id':tool_id}))

class ToolModelForm(forms.ModelForm):
    error_category = {
        'required': 'You must select a category.',
        # 'invalid': 'Wrong selection.'
    }

    identifier = forms.CharField(label="Identifier", help_text="Unique identifier to distinguish between similar tools", required=True)
    category = forms.ModelChoiceField(label="Category",queryset=ToolCategory.objects.all(), error_messages=error_category)
    
    class Meta:
        model = Tool
        fields= ('name', 'description', 'category', 'status', 'image', 'identifier', 'active', 'blackout_start_date', 'blackout_end_date')
    


@login_required(login_url='users:login')
def detail(request, tool_id):
    tool = Tool.objects.get(pk=tool_id)
    is_owner = Is_Owner( request.user.profile, tool)
    iscoordinator = False
    if tool.is_in_shed():
        shed = tool.shed
        iscoordinator = shed.iscoordinator(request.user.profile)
    if (request.method == 'GET'):
        return render(request, 'ToolMgmt/detail.html', {'tool': tool,'is_owner':is_owner,'iscoordinator':iscoordinator,})
    else:
        tool = Tool.objects.get(pk=tool_id)
        if tool.active:
            tool.active = False
        else:
            tool.active = True
        tool.save()
        return HttpResponseRedirect(reverse('toolmgmt:detail', kwargs={'tool_id': tool_id}))

toolshare/toolshare/ToolMgmt/templates/ToolMgmt/detail.html
      {% extends "base.html" %}
{% block title_html %}
  Tool detail
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %} 
    <h1>Tool Detail</h1>
    <form action="{% url 'toolmgmt:detail' tool.id %}" method="post">
      <table>
        {% csrf_token %}
        <thead>
          <tr>
            <td>ID:</td>
            <td>{{ tool.id}}</td>
          </tr>
        <tr>
            <td>Name:</td>
            <td>{{ tool.name }}</td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>{{ tool.description }}</td>
        </tr>
        <tr>
            <td>Active:</td>
            <td>{{ tool.active }}</td>
        </tr>
        <tr>
            <td>Category:</td>
            <td>{{ tool.category }}</td>
        </tr>
        <tr>
            <td>Status:</td>
            <td>{{ tool.status }}</td>
        </tr>
        <tr>
            <td>Image:</td>
            {% if tool.image %}
                <td><img src="{{ tool.image.url }}" width="300" ></td>
            {% else %}
                <td> No image found</td>
            {% endif %}
        </tr>
        </thead>
      </table>
      {% if is_owner %}
            {% if not tool.is_in_shed  %}
                <a class="button" href={% url 'sharing:tooltransfer' tool.id %}> Transfer to Shed </a>
                <a class="button" href={% url 'toolmgmt:tool_editition' tool.id %}>Edit tool</a>
                <button class="button" type="submit">Activate/Deactivate</button>
            {% endif %}
      {% endif %}
      {% if iscoordinator %}
        {% if tool.is_in_shed %}
        <a class="button" href="{%url 'sharing:returntool' tool.id%}">Return to owner</a>
        {% endif %}    
      {% endif %}

    <br>
    <a class="button" href="{% url 'toolmgmt:tools' %}">Back</a><a class="button" href={% url 'toolmgmt:tool_editition' tool.id %}>Edit tool</a>
{% endblock %}

toolshare/toolshare/ToolMgmt/templates/ToolMgmt/edit.html
{% extends "base.html" %}
{% block title_html %}
  Tool registration
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
    <h1> Tool edit </h1>
    <form  enctype="multipart/form-data" action= {% url 'toolmgmt:tool_editition' tool.id %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Edit" />
    </form>
    <a class="button" href="{% url 'toolmgmt:tools' %}">Back</a>
{% endblock %}

toolshare/toolshare/ToolMgmt/templates/ToolMgmt/index.html
{% extends "base.html" %}
{% block title_html %}
  Tool listing
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
  <h1>Tool listing</h1>
<label>Search Tool<label>
<input type="text" />
<a class="button" href="#">Search</a>
<br />
  {% if all_tools|length > 0 %}
    <table>
      <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>
          <td>Status</td>
          <td>Owner</td>
          <td>In shed</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        {% for tool in all_tools %}
        <tr>
          <td>{{ tool.id }}</td>
          <td>{{ tool.name }}</td>
          <td>{{ tool.description }}</td>
          <td>{{ tool.status }}</td>
          <td>{{ tool.owner }}</td>
          {% if tool.shed %}
            <td><a href="{% url 'sharing:sheddetail' tool.shed.id %}">{{ tool.is_in_shed }}</a></td>
          {% else %}
            <td>{{ tool.is_in_shed }}</td>
          {% endif %}
          <td>{% if tool.image %}<img src="{{ tool.image.url }}" width="100">{% else %} No image {% endif %}</td>
          <td><a class="button" href="{% url 'toolmgmt:detail' tool.id %}">Show</a></td>
          <td><a class="button" href="{% url 'sharing:create-request' tool.id %}">Ask</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <span>No tool.</span>
  {% endif %}

  <div class="pagination">
    <span class="step-links">
        {% if all_tools.has_previous %}
            <a class="button" href="?page={{ all_tools.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ all_tools.number }} of {{ all_tools.paginator.num_pages }}.
        </span>
        {% if all_tools.has_next %}
            <a class="button" href="?page={{ all_tools.next_page_number }}">next</a>
        {% endif %}
    </span>
  </div>
  <a class="button" href={% url 'toolmgmt:register' %}>New tool</a>
{% endblock %}

toolshare/toolshare/ToolMgmt/templates/ToolMgmt/mytools.html
{% extends "base.html" %}
{% block title_html %}
  Tool listing
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
  <h1>Tool listing</h1>
  {% if my_tools|length > 0 %}
    <table>
      <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>
          <td>Status</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        {% for tool in my_tools %}
        <tr>
          <td>{{ tool.id }}</td>
          <td>{{ tool.name }}</td>
          <td>{{ tool.description }}</td>
          <td>{{ tool.status }}</td>
          <td>{% if tool.image %}<img src="{{ tool.image.url }}" width="100">{% else %} No image{% endif %}</td>
          <td><a class="button" href="{% url 'toolmgmt:detail' tool.id %}">Show</a></td>
          <td><a class="button" href="{% url 'toolmgmt:tool_editition' tool.id %}">Edit</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <span>No tool.</span>
  {% endif %}

  <a class="button" href="{% url 'toolmgmt:register' %}">New tool</a>
{% endblock %}

toolshare/toolshare/ToolMgmt/templates/ToolMgmt/register.html
{% extends "base.html" %}
{% block title_html %}
  Tool registration
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
    <h1> Tool Register </h1>
    <form  enctype="multipart/form-data" action= {% url 'toolmgmt:register' %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="small button" type="submit" value="Register" />
    </form>
    <a class="small button" href="{% url 'toolmgmt:tools' %}">Back</a>
{% endblock %}