toolshare/toolshare/Sharing/urls.py
from django.conf.urls import patterns, include, url
from Sharing import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    #+++++++++++++++ URLS related to the SHED over here+++++++++++++++++++ #
    url(r'^sheds/$', views.sheds, name='sheds'),
    url(r'^sheds/create/$', views.shedcreate, name='shedcreate'),
    url(r'^sheds/(?P<shed_id>\d+)/$',views.sheddetail, name='sheddetail'),
    url(r'^sheds/(?P<shed_id>\d+)/edit/$', views.shededit, name='shededit'),
    url(r'sheds/(?P<shed_id>\d+)/coords/$', views.shedcoords, name='shedcoords'),
    url(r'sheds/(?P<shed_id>\d+)/coords/add/$',views.shedaddcoords,name='shedaddcoords'),
    url(r'sheds/tooltransfer/(?P<tool_id>\d+)/$',views.tooltransfer,name = 'tooltransfer'),
    url(r'sheds/returntool/(?P<tool_id>\d+)/$',views.returntool,name = 'returntool'),
    #+++++++++++++++++SHED url ends here ++++++++++++++++++++++++++++++++++#
    url(r'^$', RedirectView.as_view(url='received-requests/', permanent=False), name='received-requests'),
    url(r'^create-request/(?P<tool_id>\d+)/$', views.create_request, name='create-request'),
    url(r'^create-sharing/(?P<tool_request_id>\d+)/$', views.create_sharing, name='create-sharing'),
    url(r'^received-requests/$', views.received_requests_index, name='received-requests'),
    url(r'^received-requests-coordinator/$', views.received_requests_coordinator_index, name='received-requests-coordinator'),
    url(r'^asked-requests/$', views.asked_requests_index, name='asked-requests'),
    url(r'^received-requests/(?P<tool_request_id>\d+)/$', views.received_request_detail, name='received-request-detail'),
    url(r'^asked-requests/(?P<tool_request_id>\d+)/$', views.asked_request_detail, name='asked-request-detail'),
    url(r'^asked-requests/(?P<tool_request_id>\d+)/edit$', views.asked_request_edit, name='asked-request-edit'),
    url(r'^given-tools/$', views.given_tools_index, name='given-tools'),
    url(r'^given-tools-coordinator/$', views.given_tools_coordinator_index, name='given-tools-coordinator'),
    url(r'^given-tools/(?P<tool_sharing_id>\d+)/$', views.given_tool_edit, name='given-tool-edit'),
    url(r'^borrowed-tools/$', views.borrowed_tools_index, name='borrowed-tools'),
    #++++++++++++++++++++Statistics ++++++++++++++++++++++++++++++++++++++++++++++++++++++#
    url(r'^statistics/$',views.statistics,name = "statistics"),
    #+++++++++++++++++++Search Tool Functionality ++++++++++++++++++++++++++#
    url(r'^searchtools/$', views.searchtools , name = 'searchtools'),
)

toolshare/toolshare/UserAuth/urls.py
from django.conf.urls import patterns,url
from UserAuth import views

urlpatterns = patterns('' ,
        url(r'^signup/$', views.sign_up, name='sign_up'),
        url(r'^login/$',views.user_login, name='login'),
        url(r'^$',views.user_login, name='login'),
        url(r'^edit/$',views.user_edit, name='edit'),
        url(r'^logout/$',views.user_logout, name='logout'),
        url(r'^preferences/$',views.user_preferences, name = 'preferences'), 
        url(r'^changepassword/$',views.changepassword, name = 'change_password'),
        )

toolshare/toolshare/toolshare/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='home/'), name='home'),
    url(r'^home/', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('UserAuth.urls',namespace="users")),
    url(r'^toolmgmt/', include('ToolMgmt.urls', namespace="toolmgmt")),
    url(r'^sharing/', include('Sharing.urls', namespace="sharing")),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
)

toolshare/toolshare/toolshare/templates/toolshare/about.html
{% extends "base.html" %}
{% block title_html %}
  About
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
<div class="large-8 rows">
<div class="large-12 columns">
<div id="featured" data-orbit>
<img src="http://www.hisiafurniture.com/wp-content/uploads/2014/09/striking-tools-1024x768.jpg" alt="slide image">
<img src="http://cycology371.com/wp-content/uploads/2014/08/IMG_1133.2-1024x768.jpg" alt="slide image">
<img src="http://cdn2.business2community.com/wp-content/uploads/2013/11/tools.jpg" alt="slide image">
</div>
</div>
</div>
    <h1>About</h1>
    <p>
      Group Five 2014
      <br>
      Vishnu Tej MP - Team Co-ordinator
      <br>
      Ziyi Bai - Development Co-ordinator
      <br>
      Priyank Kapadia - Development Co-ordinator
      <br>
      Hector Valdecantos - Requirements Co-ordinator
      <br>
      Antar Vasi - Test Co-ordinator
    </p>
{% endblock %}

toolshare/toolshare/toolshare/templates/toolshare/base.html
<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title> {% block title_html %} {% endblock %}</title>
<meta name="description" content="Documentation and reference library for ZURB Foundation. JavaScript, CSS, components, grid and more."/>
<meta name="author" content="ZURB, inc. ZURB network also includes zurb.com"/>
<meta name="copyright" content="ZURB, inc. Copyright (c) 2014"/>
<link rel="stylesheet" type="text/css" href="https://rawgit.com/xdan/datetimepicker/master/jquery.datetimepicker.css"/>
<link rel="stylesheet" href="http://foundation.zurb.com/assets/css/templates/foundation.css"/>
<script src="http://foundation.zurb.com/assets/js/modernizr.js"></script>
</head>
<body>
 
<nav class="top-bar" data-topbar>
<ul class="title-area">
</ul>
<section class="top-bar-section">
<ul class="left">
<li class="divider"></li>
<li><a href="/home">Home</a></li>
<li class="divider"></li>
<li><a href="/about" >About</a></li>
<li class="divider"></li>
</ul>
{% if user.is_authenticated %}
<ul class="left">
  <li class="divider"></li>
  <li><a href="/toolmgmt/tools" >Tool Listing</a></li>
  <li class="divider"></li>
  <li><a href="/toolmgmt/tools/mytools" >My Tools</a></li>
  <li class="divider"></li>
  <li><a href="/sharing/sheds" >Sheds</a></li>
  <li class="divider"></li>

  <li class="has-dropdown">
    <a href="#">
      {% if user.profile.has_waiting_received_requests %}<font color="red">O </font>{% endif %}
      {% if user.profile.has_waiting_received_requests_in_shed %}<font color="green">O </font>{% endif %}
      Requests
    </a>
    <ul class="dropdown">
      {% if user.profile.is_coordinator %}
      <li><a href={% url 'sharing:received-requests-coordinator' %}>Received requests (to sheds)</a></li>
      <li class="divider"></li>
      {% endif %}
      <li><a href={% url 'sharing:received-requests' %}>Received requests</a></li>
      <li><a href={% url 'sharing:asked-requests' %}>Asked requests</a></li>
    </ul>
  </li>
   <li class="divider"></li>
  <li class="has-dropdown">
    <a href="#">
      {% if user.profile.has_current_given_tools %}<font color="red">O </font>{% endif %}
      {% if user.profile.has_current_given_tools_in_shed %}<font color="green">O </font>{% endif %}
      Sharing
    </a>
    <ul class="dropdown">
      {% if user.profile.is_coordinator %}
      <li><a href={% url 'sharing:given-tools-coordinator' %}>Given tools (from sheds)</a></li>
      <li class="divider"></li>
      {% endif %}
      <li><a href={% url 'sharing:given-tools' %}>Given tools</a></li>
      <li><a href={% url 'sharing:borrowed-tools' %}>Borrowed tools</a></li>
    </ul>
  </li>
  <li>
      <a href="{%url 'sharing:statistics' %}"> Statistics </a>
  </li>
</ul>

<ul class="right">
<li class="has-dropdown">
<a href="#"> {{ user.username }} </a>
<ul class="dropdown">
<li><a href={% url 'users:edit' %}>Edit Profile</a></li>
<li class="divider"></li>
<li><a href={% url 'users:logout' %}>Logout</a></li>
</ul>
</li>
</ul>
{% else %}
<ul class="right">
<li class="divider"></li>
<li><a href="/users/login/">Login</a></li>
</ul>
{% endif %}
</ul>
</section>
</nav> 

</br>
<div class="row">
<div class="large-12 columns">
<style>
  li {color: #008CBA;
      font-family: Helvetica;
      font-weight: normal;}
</style>
<nav class="top-bar" data-topbar>
<ul class="title-area">
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %} >{{ message }}</li>
{% endfor %}
</ul>
{% endif %}
</ul>
</nav> 
</div>
</div>

</br>

</div>
 
<div class="row">
<div class="large-4 columns">
</div>
<div class="large-8 columns">
<h4>{% block h1 %}{% endblock %}</h4>
<div class="row">
<div class="large-6 columns">
</div>
</div>
</div>
</div>
 
<div class="row">
<div class="large-12 columns">
<h4>{% block article_content %}{% endblock %}</h4>
</div>
<div class="large-4 columns">
</div>
</div>
 
<footer class="row">
<div class="large-12 columns">
<hr/>
<div class="row">
<div class="large-6 columns">
<p>&copy; SWEN 610 - TEAM5 - RIT, Rochester, NY - 2014</p>
</div>
</div>
</div>
</footer>
<script>
  document.write('<script src=js/vendor/' +
  ('__proto__' in {} ? 'zepto' : 'jquery') +
  '.js><\/script>')
  </script>
<script src="http://foundation.zurb.com/assets/js/jquery.js"></script>
<script src="js/foundation.min.js"></script>
<script>
    $(document).foundation();
  </script>
<script src="http://foundation.zurb.com/assets/js/templates/jquery.js"></script>
<script src="http://foundation.zurb.com/assets/js/templates/foundation.js"></script>
<script>
      $(document).foundation();

      var doc = document.documentElement;
      doc.setAttribute('data-useragent', navigator.userAgent);
    </script>
<script src="https://rawgit.com/xdan/datetimepicker/master/jquery.js"></script>
<script src="https://rawgit.com/xdan/datetimepicker/master/jquery.datetimepicker.js"></script>
<script>

$('#datetimepicker').datetimepicker({
dayOfWeekStart : 1,
lang:'en',
disabledDates: "{{ tool.blackout_dates }}",
startDate:  '2014/12/08',
format: 'Y-m-d H:i'
});
$('#datetimepicker2').datetimepicker({
dayOfWeekStart : 1,
lang:'en',
disabledDates: "{{ tool.blackout_dates }}",
startDate:  '2014/12/08',
format: 'Y-m-d H:i'
});

</script>
</body>
</html>

toolshare/toolshare/toolshare/templates/toolshare/home.html
{% extends "base.html" %}
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title> {% block title_html %} Home {% endblock %}</title>
<meta name="description" content="Documentation and reference library for ZURB Foundation. JavaScript, CSS, components, grid and more."/>
<meta name="author" content="ZURB, inc. ZURB network also includes zurb.com"/>
<meta name="copyright" content="ZURB, inc. Copyright (c) 2014"/>
<link rel="stylesheet" href="http://foundation.zurb.com/assets/css/templates/foundation.css"/>
<script src="http://foundation.zurb.com/assets/js/modernizr.js"></script>
{% block h1 %}
  {{ bloc.super }}
{% endblock %}

{% block article_content %}
<div class="large-8 rows">
<div class="large-12 columns">
<div id="featured" data-orbit>
<img src="http://www.hisiafurniture.com/wp-content/uploads/2014/09/striking-tools-1024x768.jpg" alt="slide image">
<img src="http://cycology371.com/wp-content/uploads/2014/08/IMG_1133.2-1024x768.jpg" alt="slide image">
<img src="http://cdn2.business2community.com/wp-content/uploads/2013/11/tools.jpg" alt="slide image">
</div>
</div>
</div>
    <h1>Toolshare Web application</h1>
    <p>
      Welcome to toolshare.
      <br>
      The application used to share tools in your neighborhood within your community
    </p>
{% endblock %}
<script>
  document.write('<script src=js/vendor/' +
  ('__proto__' in {} ? 'zepto' : 'jquery') +
  '.js><\/script>')
  </script>
<script src="http://foundation.zurb.com/assets/js/jquery.js"></script>
<script src="js/foundation.min.js"></script>
<script>
    $(document).foundation();
  </script>
<script src="http://foundation.zurb.com/assets/js/templates/jquery.js"></script>
<script src="http://foundation.zurb.com/assets/js/templates/foundation.js"></script>
<script>
      $(document).foundation();

      var doc = document.documentElement;
      doc.setAttribute('data-useragent', navigator.userAgent);
    </script>