toolshare/toolshare/Sharing/urls.py
from django.conf.urls import patterns, include, url
from Sharing import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    #+++++++++++++++ URLS related to the SHED over here+++++++++++++++++++ #
    url(r'^sheds/$', views.sheds, name='sheds'),
    url(r'^sheds/create/$', views.shedcreate, name='shedcreate'),
    url(r'^sheds/(?P<shed_id>\d+)/$',views.sheddetail, name='sheddetail'),
    url(r'^sheds/(?P<shed_id>\d+)/edit/$', views.shededit, name='shededit'),
    url(r'sheds/(?P<shed_id>\d+)/coords/$', views.shedcoords, name='shedcoords'),
    url(r'sheds/(?P<shed_id>\d+)/coords/add/$',views.shedaddcoords,name='shedaddcoords'),
    url(r'sheds/tooltransfer/(?P<tool_id>\d+)/$',views.tooltransfer,name = 'tooltransfer'),
    url(r'sheds/returntool/(?P<tool_id>\d+)/$',views.returntool,name = 'returntool'),
    #+++++++++++++++++SHED url ends here ++++++++++++++++++++++++++++++++++#
    url(r'^$', RedirectView.as_view(url='received-requests/', permanent=False), name='received-requests'),
    url(r'^create-request/(?P<tool_id>\d+)/$', views.create_request, name='create-request'),
    url(r'^create-sharing/(?P<tool_request_id>\d+)/$', views.create_sharing, name='create-sharing'),
    url(r'^received-requests/$', views.received_requests_index, name='received-requests'),
    url(r'^received-requests-coordinator/$', views.received_requests_coordinator_index, name='received-requests-coordinator'),
    url(r'^asked-requests/$', views.asked_requests_index, name='asked-requests'),
    url(r'^received-requests/(?P<tool_request_id>\d+)/$', views.received_request_detail, name='received-request-detail'),
    url(r'^asked-requests/(?P<tool_request_id>\d+)/$', views.asked_request_detail, name='asked-request-detail'),
    url(r'^asked-requests/(?P<tool_request_id>\d+)/edit$', views.asked_request_edit, name='asked-request-edit'),
    url(r'^given-tools/$', views.given_tools_index, name='given-tools'),
    url(r'^given-tools-coordinator/$', views.given_tools_coordinator_index, name='given-tools-coordinator'),
    url(r'^given-tools/(?P<tool_sharing_id>\d+)/$', views.given_tool_edit, name='given-tool-edit'),
    url(r'^borrowed-tools/$', views.borrowed_tools_index, name='borrowed-tools'),
    #++++++++++++++++++++Statistics ++++++++++++++++++++++++++++++++++++++++++++++++++++++#
    url(r'^statistics/$',views.statistics,name = "statistics"),
    #+++++++++++++++++++Search Tool Functionality ++++++++++++++++++++++++++#
    url(r'^searchtools/$', views.searchtools , name = 'searchtools'),
)

toolshare/toolshare/ToolMgmt/urls.py
from django.conf.urls import patterns, include, url
from ToolMgmt import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='tools/', permanent=False), name='tools'),
    url(r'^tools/$', views.index, name='tools'),
    url(r'^tools/mytools/', views.mytools, name='mytools'),
    url(r'^tools/register/$', views.register, name="register"),
    url(r'^tools/(?P<tool_id>\d+)/$', views.detail, name='detail'),
    url(r'^tools/(?P<tool_id>\d+)/edit/$', views.tool_edit, name='tool_editition'),
)

toolshare/toolshare/toolshare/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='home/'), name='home'),
    url(r'^home/', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('UserAuth.urls',namespace="users")),
    url(r'^toolmgmt/', include('ToolMgmt.urls', namespace="toolmgmt")),
    url(r'^sharing/', include('Sharing.urls', namespace="sharing")),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
)

toolshare/toolshare/Sharing/forms.py
from django import forms
from django.contrib.auth.models import User
from Sharing.models import Shed
from UserAuth.models import UserProfile
from localflavor.us.forms import USZipCodeField
from localflavor.us.forms import USStateField
from django.forms import ModelForm
from django.core.files.images import get_image_dimensions
import pdb
class ShedCreateForm(forms.ModelForm):
    class Meta:
        model = Shed
        fields = ('name','description')

class ShedEditForm(forms.ModelForm):
    coordinators = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Shed
        fields = ('name','description', 'coordinators')

toolshare/toolshare/Sharing/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from UserAuth.models import UserProfile
from ToolMgmt.models import Tool
from ToolMgmt.utils import Is_Owner
from Sharing.models import Shed, ShareZone
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from .forms import ShedCreateForm, ShedEditForm
from django.forms import ModelForm
from django.shortcuts import render_to_response
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import pdb
from django.core.exceptions import ObjectDoesNotExist
from Sharing.models import Arrangement, Request, Sharing
from django import forms
from django.db.models import Q
import datetime
from django.utils.timezone import utc
from .utils import GetMostUsedTool,GetFrequentBorrower,GetFrequentLender,TotalTools,TotalUsers,TotalSheds, get_top_borrower_rating
# Create your views here.
##++++++++++++++All things related to Shed here++++++++++++++++##
@login_required(login_url='users:login')
def shedcoords(request,shed_id):
    return HttpResponse("List all shed coordinators here")

@login_required(login_url='users:login')
def shedaddcoords(request,shed_id):
    return HttpResponse("Add Shed coorinators here")

@login_required(login_url='users:login')
def sheds(request):
    profile = UserProfile.objects.get(user = request.user) 
    sharezone = ShareZone.objects.get(pk = profile.sharezone.id)
    if not Shed.objects.filter(sharezone = profile.sharezone):
        all_sheds = [] 
    else:
        all_sheds = sharezone.sheds.all()

    paginator = Paginator(all_sheds, 6)
    page = request.GET.get('page')

    try:
        paged_tools = paginator.page(page)
    except PageNotAnInteger:
        paged_tools = paginator.page(1)
    except EmptyPage:
        paged_tools = paginator.page(paginator.num_pages)

    return render(request, 'Sharing/sheds.html', {'all_sheds': paged_tools})


@login_required(login_url='users:login')
def shedcreate(request):
    context = RequestContext(request)
    profile = UserProfile.objects.get(user = request.user) 
    if request.POST:
        form = ShedCreateForm(request.POST)
        newshed = form.save(commit = False)
        newshed.sharezone = ShareZone.objects.get(zipcode = profile.sharezone.zipcode)
        newshed.save()
        newshed.coordinators.add(profile)
        newshed.save()

        messages.add_message(request,messages.SUCCESS,"Shed %s created!" %newshed)
        return HttpResponseRedirect(reverse('sharing:sheddetail',kwargs={'shed_id': newshed.id}))
    else:
        form =  ShedCreateForm()
        return render_to_response('Sharing/shedcreate.html', {'form': form}, context)


@login_required(login_url='users:login')
def sheddeactivate(request):
    return HttpResponse("Shed Deactivate")

@login_required(login_url='users:login')
def shededit(request,shed_id):
    if request.user.profile in Shed.objects.get(pk=shed_id).coordinators.all():
        print(request.user.profile.sheds.all()) 
        shed = Shed.objects.get(pk=shed_id)
        if not shed:
            return HttpRespone("No shed ")
        else:
            form = ShedEditForm()
            context = RequestContext(request)
            if request.POST:
                form = ShedEditForm(request.POST, instance = shed)
                shedchange = form.save(commit=False)
                shedchange.sharezone = request.user.profile.sharezone
                shedchange.save()
                form.save_m2m()
                messages.add_message(request,messages.SUCCESS,"Shed information changed successfully")
                return HttpResponseRedirect(reverse('sharing:sheddetail',kwargs={'shed_id':shedchange.id}))
            else:
                form = ShedEditForm(instance = shed)
                return render_to_response('Sharing/shededit.html',{'form':form,'shed':shed}, context)
    else:
        return HttpResponse("You are not authorised to view the shed or the shed does not exist at all.")

@login_required(login_url='users:login')
def sheddetail(request,shed_id):
    profile = UserProfile.objects.get(user = request.user)
    if profile in Shed.objects.get(pk=shed_id).coordinators.all():
        is_coord = True
    else:
        is_coord = False

    if request.POST:
        pass
    else:
        shed = Shed.objects.get(pk=shed_id)
        return render(request, 'Sharing/sheddetail.html', {'shed': shed,'is_coord':is_coord})

@login_required(login_url='users:login')
def tooltransfer(request,tool_id):
    tool = Tool.objects.get(pk = tool_id)
    if Is_Owner(request.user.profile , tool):
        if request.POST:
            shedid = request.POST['shed']
            if shedid:
                try:
                    shed = Shed.objects.get(pk=shedid)
                    tool.shed = shed
                    tool.save()
                    messages.add_message(request,messages.SUCCESS,"Tool transfered successfully!")
                    return HttpResponseRedirect(reverse('toolmgmt:tools'))
                except DoesNotExist:
                    raise Http404
            else:
                messages.add_message(request,messages.ERROR,"There was an error in retrieving the shed information")
                return HttpResponseRedirect(reverse('toolmgmt:tools'))
        else:
            context = RequestContext(request)
            my_sharezone = request.user.profile.sharezone
            my_sheds = my_sharezone.sheds.all()
            return render_to_response('Sharing/transfertool.html',{'mysheds':my_sheds,'tool':tool},context)
    else:
        messages.add_message(request,messages.ERROR,"You are not authorised to perform actions on this tool")
        return HttpResponseRedirect(reverse('toolmgmt:detail',kwargs = {'tool_id':tool_id}))  

@login_required(login_url='users:login')
def returntool(request,tool_id):
    tool = Tool.objects.get(pk = tool_id)
    if (tool.is_in_shed()):
        shed = tool.shed
        if shed.iscoordinator(request.user.profile):
            tool.shed = None
            tool.save()
            messages.add_message(request,messages.SUCCESS,"Tool returned successfully")
            return HttpResponseRedirect(reverse('toolmgmt:tools'))  
        else:
            messages.add_message(request,messages.ERROR,"You are not authorised to return the tool")
            return HttpResponseRedirect(reverse('toolmgmt:detail',kwargs = {'tool_id':tool_id}))  
######+++++++++++++++All things related to Shed end here+++++++++++++++#########
#######++++++++++++++All things related to search here +++++++++++++++++########
def searchtools(request):

    return HttpResponse("searchtools")


#########+++++++++++++All things related to search ends here ++++++++++++########
def create_request(request, tool_id):
    context = RequestContext(request)
    tool = Tool.objects.get(id = tool_id)
    if request.POST:
        form = RequestModelForm(request.POST)
        form.fields['start_date'].widget.attrs['id'] = 'datetimepicker'
        form.fields['end_date'].widget.attrs['id'] = 'datetimepicker2'
        if form.is_valid():
            from_date = request.POST['start_date']
            to_date = request.POST['end_date']
            if tool.is_available(from_date, to_date):
                new_request = form.save(commit=False)
                new_request.pickup_arrangement = tool.owner.pickup_loc
                new_request.borrower = request.user.profile
                new_request.lender = tool.owner
                new_request.tool = tool
                new_request.save()
                form.save_m2m()
                messages.add_message(request, messages.SUCCESS, 'Tool %s was successfully requested to %s' % (tool, new_request.lender))
                return HttpResponseRedirect(reverse('sharing:asked-requests'))
            else:
                messages.add_message(request, messages.ERROR, 'Tool %s is not available for dates: %s to %s' % (tool, from_date, to_date))
                return render_to_response('Sharing/create_request.html', {'form': form, 'tool': tool}, context)
        else:
            return render_to_response('Sharing/create_request.html', {'form': form, 'tool': tool}, context)
    else:
        print("GET")
        form = RequestModelForm()
        form.fields['start_date'].widget.attrs['id'] = 'datetimepicker'
        form.fields['end_date'].widget.attrs['id'] = 'datetimepicker2'
        return render_to_response('Sharing/create_request.html', {'form': form, 'tool': tool}, context)

class RequestModelForm(forms.ModelForm):
    class Meta:
        model = Request
        fields= ( 'start_date', 'end_date','msg')
    def clean(self):
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')
        if not (isinstance(start_date, datetime.date) and isinstance(end_date, datetime.date)):
            raise forms.ValidationError("You should enter valid dates")
        if start_date > end_date:
            raise forms.ValidationError("Start date cannot be greater that end date")
        now = datetime.datetime.utcnow().replace(tzinfo=utc)
        if start_date < now:
            raise forms.ValidationError("Start date cannot be lower than now")
        return self.cleaned_data

def asked_requests_index(request):
    now = datetime.datetime.utcnow().replace(tzinfo=utc)
    waiting_requests = Request.objects.filter(borrower=request.user.profile).filter(approved=False).filter(end_date__gte=now).order_by('-start_date')
    approved_requests = Request.objects.filter(Q(borrower=request.user.profile) & Q(approved=True) &
                                               Q(end_date__gte=now) & Q(sharing__isnull=True)).order_by('-start_date')
    past_requests = Request.objects.filter(Q(borrower=request.user.profile) &

toolshare/toolshare/Sharing/templates/Sharing/asked_request_edit.html
{% extends "base.html" %}
{% block title_html %}
  Tool request detail
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %} 


  <h1> Tool edit </h1>
  <form  enctype="multipart/form-data" action= {% url 'sharing:asked-request-edit' tool_request.id %} method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="button" type="submit" value="Edit" /> <a class="small button" href="{{back}}">Cancel</a>
  </form>
  
{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/asked_requests_index.html
{% extends "base.html" %}
{% block title_html %}
  Tool listing
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
  <h1>Asked requests</h1>
  <table>
    <thead>
      <tr>
        <td>Request</td>
        <td></td>
        <td>From</td>
        <td>To</td>
        <td>Accepted</td>
        <td></td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    {% for request in waiting_requests %}
      <tr>
        <td>{{ request }}</td>
        <td>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="100">{% else %} No image{% endif %}</td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td>{{ request.approved }}</td>
        <td><a href={% url 'sharing:asked-request-detail' request.id %}>Show</a></td>
        <td><a href={% url 'sharing:asked-request-edit' request.id %}>Edit</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h1>Approved asked requests</h1>
  <table>
    <thead>
      <tr>
        <td>Request</td>
        <td></td>
        <td>From</td>
        <td>To</td>
        <td>Accepted</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    {% for request in approved_requests %}
      <tr>
        <td>{{ request }}</td>
        <td>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="100">{% else %} No image{% endif %}</td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td>{{ request.approved }}</td>
        <td><a href={% url 'sharing:asked-request-detail' request.id %}>Show</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h4>Past Asked request listing</h4>
  <table>
    <thead>
      <tr>
        <td>Request</td>
        <td></td>
        <td>From</td>
        <td>To</td>
        <td>Accepted</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    {% for request in past_requests %}
      <tr>
        <td>{{ request }}</td>
        <td>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="50">{% else %} No image{% endif %}</td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td>{{ request.approved }}</td>
        <td><a href={% url 'sharing:asked-request-detail' request.id %}>Show</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/borrowed_tools.html
{% extends "base.html" %}
{% block title_html %}
  Borrowed tools from the community
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
  
  <h1>Current borrowed tools</h1>
  <table>
    <thead>
      <tr>
        <td>Lender</td>
        <td>tool</td>
        <td>From</td>
        <td>To</td>
        <td>Returned</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    {% for request in current_borrowed_tools %}
      <tr>
        <td>{{ request.lender }}</td>
        <td>

          <div>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="100">{% else %} No image {% endif %} | {{ request.tool.name }} </div>
        </td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td>{{ request.returned }}</td>
        <td><a href={% url 'sharing:given-tool-edit' request.id %}>End sharing...</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h1>Past borrowed tools</h1>
  <table>
    <thead>
      <tr>
        <td>lender</td>
        <td>tool</td>
        <td>From</td>
        <td>To</td>
        <td>Returned</td>
        <td>Comment</td>
        <td>Rated</td>
      </tr>
    </thead>
    <tbody>
    {% for request in past_borrowed_tools %}
      <tr>
        <td>{{ request.lender }}</td>
        <td>

          <div>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="100">{% else %} No image {% endif %} | {{ request.tool.name }} </div>
        </td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td>{{ request.returned }}</td>
        <td>{{ request.sharing_comment }} </td>
        <td>{{ request.rated }} </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/create_request.html
{% extends "base.html" %}
<head>
{% block title_html %}
  Tool registration
{% endblock %}

<script type="text/javascript">
$(document).ready(function() {
    alert("hi");
});
</script>
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
</head>
{% block article_content %}
    <form action= {% url 'sharing:create-request' tool.id %} method="post" >
        {% csrf_token %}
        <table>
          <tr>
            <td>{% if tool.image %}<img src="{{ tool.image.url }}" width="300">{% else %} No image {% endif %}</td>
            <td>owner: {{ tool.owner }} </td>
            <td>pickup arrangement: {{ tool.owner.pickup_loc }} </td>
          </tr>
        </table>
        {{form.as_p}}
        <input class="button" type="submit" value="Request" />
    </form>
{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/create_sharing.html
{% extends "base.html" %}
{% block title_html %}
  Tool sharing
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
    <form  action= {% url 'sharing:create-sharing' tool_request.id %} method="post">
        {% csrf_token %}
        <table>
          <tr>
            <td>{% if tool_request.tool.image %}<img src="{{ tool_request.tool.image.url }}" width="200">{% else %} No image{% endif %}</td>
            <td><b>lender:</b> <br>{{ tool_request.lender }} <br> (rate: {{ tool_request.lender.rate }})</td>
            <td><b>borrower:</b> <br> {{ tool_request.borrower }} <br> (rate: {{ tool_request.borrower.rate }}) </td>
            <td><b>pickup arrengement:</b> <br>{{ tool_request.lender.pickup_loc }} </td>
            <td><b>Start date:</b> <br>{{ tool_request.start_date }} </td>
            <td><b>End date:</b> <br>{{ tool_request.end_date }} </td>
          </tr>
        </table>
        {{ form.as_p }}
        <input class="button" type="submit" value="Share" /> <a class="button" href="{{back}}">Cancel</a>

    </form>
{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/given_tool_edit.html
{% extends "base.html" %}
{% block title_html %}
  Tool sharing detail
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %} 


  <h1> Tool sharing edit </h1>
  <form  enctype="multipart/form-data" action= {% url 'sharing:given-tool-edit' tool_sharing.id %} method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="button" type="submit" value="Submit" /> <a class="small button" href="{{back}}">Cancel</a>
  </form>
  
{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/received_requests_index.html
{% extends "base.html" %}
{% block title_html %}
  Tool listing
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
  
  <h1>Received requests (waiting)</h1>
  <table>
    <thead>
      <tr>
        <td>Request</td>
        <td></td>
        <td>From</td>
        <td>To</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    {% for request in waiting_requests %}
      <tr>
        <td>{{ request }}</td>
        <td>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="100">{% else %} No image {% endif %}</td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td><a href={% url 'sharing:received-request-detail' request.id %}>Detail/Approve...</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h1>Approved received requests</h1>
  <table>
    <thead>
      <tr>
        <td>Request</td>
        <td></td>
        <td>From</td>
        <td>To</td>
        <td></td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    {% for request in approved_requests %}
      <tr>
        <td>{{ request }}</td>
        <td>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="50">{% else %} No image {% endif %}</td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td><a href={% url 'sharing:received-request-detail' request.id %}>Detail/Approve...</a></td>
        <td><a href={% url 'sharing:create-sharing' request.id %}>Start sharing...</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h4>Past requests</h4>
  <table>
    <thead>
      <tr>
        <td>Request</td>
        <td></td>
        <td>From</td>
        <td>To</td>
        <td>Approved</td>
      </tr>
    </thead>
    <tbody>
    {% for request in past_requests %}
      <tr>
        <td>{{ request }}</td>
        <td>{% if request.tool.image %}<img src="{{ request.tool.image.url }}" width="50">{% else %} No image{% endif %}</td>
        <td>{{ request.start_date }}</td>
        <td>{{ request.end_date }}</td>
        <td>{{ request.approved }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/shedcreate.html
{% extends "base.html" %}
{% block title_html %}
  Create Your own Shed!
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
<h1>Create Your own Shed!</h1>
    <form  enctype="multipart/form-data" action= {% url 'sharing:shedcreate' %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Create" />
    </form>
    <br>
    <a class="button" href="{% url 'sharing:sheds' %}">Back</a>
{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/sheddetail.html
{% extends "base.html" %}
{% block title_html %}
 Shed detail
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %} 
<h1>{{shed.name}}</h1>
    <form action="{% url 'sharing:sheddetail' shed.id %}" method="post">
      <table>
        {% csrf_token %}
        <thead>
        <tr>
            <td>Name:</td>
            <td>{{ shed.name }}</td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>{{ shed.description }}</td>
        </tr>
        </thead>
      </table>
  <h3>Tools in shed</h3>
  {%if shed.tools.all|length > 0 %}
  <table>
      <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>
          <td>Status</td>
          <td>Owner</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        {% for tool in shed.tools.all %}
        <tr>
          <td>{{ tool.id }}</td>
          <td>{{ tool.name }}</td>
          <td>{{ tool.description }}</td>
          <td>{{ tool.status }}</td>
          <td>{{ tool.owner }}</td>
          <td>{% if tool.image %}<img src="{{ tool.image.url }}" width="100">{% else %} No image{% endif %}</td>
          <td><a class="button" href="{% url 'toolmgmt:detail' tool.id %}">Show</a></td>
          <td><a class="button" href="{% url 'sharing:create-request' tool.id %}">Ask</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <span>No tool.</span>
  {% endif %}

        <br/>
  <h3>Coordinators</h3>
  <table>
    {% for coordinator in shed.coordinators.all %}
      <tr>
        <td>{{ coordinator }}</td>
      </tr>
    {% endfor %}
  </table>

  {%if is_coord %}
      <a class="button" href="{% url 'sharing:shededit' shed.id %}">Edit</a>
        {% else %}
        Not a coordinator
  {% endif %}

{% endblock %}

toolshare/toolshare/Sharing/templates/Sharing/shededit.html
{% extends "base.html" %}
{% block title_html %}
  Tool registration
{% endblock %}
{% block h1 %}
  {{ bloc.super }}
{% endblock %}
{% block article_content %}
<h1> Shed edit </h1>
    <form  enctype="multipart/form-data" action="{% url 'sharing:shededit' shed.id  %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Save Changes" />
    </form>
    <a class="button" href="{% url 'sharing:sheddetail' shed.id %}">Back</a>
{% endblock %}